#!/usr/bin/env bash

apk add --no-cache \
    nginx \
    php5-curl \
    php5-fpm \
    php5-ldap \
    php5-mcrypt \
    php5-json \
    php5-xml \
    php5-zlib \
    git \
    tzdata \
    supervisor \
    ssmtp

mkdir -p /var/log/php-fpm
